from Final_DL import train, trainX, trainY, valX, valY
import argparse
parser = argparse.ArgumentParser(description='Run my model function')
parser.add_argument('-wp','--wandb_project', default="CS6910_Assignment-1", required=False,metavar="", type=str, help=' ')
parser.add_argument('-we','--wandb_entity', default="Pankaj Rawat", required=False,metavar="", type=str, help='')
parser.add_argument('-d','--dataset', default="fashion_mnist", required=False,metavar="", type=str,choices= ["mnist", "fashion_mnist"], help=' ')
parser.add_argument('-e','--epochs', default=40, required=False,metavar="", type=int, help=' ')
parser.add_argument('-b','--batch_size', default=128, required=False,metavar="", type=int, help=' ')
parser.add_argument('-o','--optimizer', default="rmsprop", required=False,metavar="", type=str,choices= ["sgd", "momentum", "nag", "rmsprop", "adam", "nadam"], help=' ')
parser.add_argument('-l','--loss', default="cross_entropy", required=False,metavar="", type=str,choices= ["mean_squared_error", "cross_entropy"], help=' ')
parser.add_argument('-lr','--learning_rate', default=0.001, required=False,metavar="", type=int, help='')
parser.add_argument('-m','--momemtum', default=0.9, required=False,metavar="", type=int, help=' ')
parser.add_argument('-beta','--beta', default=0.9, required=False,metavar="", type=int, help=' ')
parser.add_argument('-beta1','--beta1', default=0.9, required=False,metavar="", type=int, help=' ')
parser.add_argument('-beta2','--beta2', default=0.99, required=False,metavar="", type=int, help=' ')
parser.add_argument('-eps','--epsilon', default=0.00001, required=False,metavar="", type=int, help=' ')
parser.add_argument('-w_d','--weight_decay', default=.0, required=False,metavar="", type=int, help=' ')
parser.add_argument('-w_i','--weight_init', default="Xavier", required=False,metavar="", type=str,choices= ["random", "Xavier"], help=' ')
parser.add_argument('-nhl','--num_layers', default=6, required=False,metavar="", type=int, help=' ')
parser.add_argument('-sz','--hidden_size', default=128, required=False,metavar="", type=int, help=' ')
parser.add_argument('-a','--activation', default="tanh", required=False,metavar="", type=str,choices= ["identity", "sigmoid", "tanh", "ReLU"], help=' ')
args = parser.parse_args()
layers = [args.hidden_size] * (args.num_layers+1)
layers[0] = 28*28
layers.append(10)
train(layers, trainX, trainY, valX, valY, args.epochs, args.learning_rate, args.activation, args.optimizer, args.batch_size, args.weight_init, args.weight_decay, args.loss, args.momemtum , args.beta ,args.beta1 ,args.beta2 ,args.epsilon)
